staging:
  application: "appconvocatoria"
  repo_url: "https://github.com/afleones/appconvocatoria.git"
  deploy_to: "/home/web/apps/appconvocatoria"
  ssh_port: 22
  server: "3.87.160.195"
  # server_name: "mydomain.com"
  db_server: "localhost"
  user: "root"
  db_user: "appconvocatoria"
  db_user: "root"
  db_password: ""
